services:
  api:
    build:
      dockerfile: ./api/Dockerfile
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    user: root
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    working_dir: /app
    env_file:
      - ./api/.env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:123@db:5432/ecom_app
    networks:
      - ecom
  
  db:
    image: postgres:16.2-bullseye
    user: root
    environment:
      POSTGRES_DB: ecom_app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_HOST: localhost
    ports:
      - "5432:5432"
    volumes:
      - ./dumpfile.sql:/docker-entrypoint-initdb.d/dumpfile.sql
      - data:/var/lib/postgresql/data
    networks:
      - ecom

  client:
    build:
      dockerfile: ./client/Dockerfile
    command: bash -c "npm install && npm run dev"
    volumes:
      - ./client:/app
    ports:
      - "5173:5173"
    networks:
      - ecom

volumes:
  data:


networks:
  ecom:
    driver: bridge