services:
  api:
    image: python:3
    command: sh -c "python manage.py migrate && python manage.py runserver"
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    working_dir: /app
    env_file:
      - ./api/.env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:123@db:5432/ecom_app
    networks:
      - ecom
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ecom_app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_HOST: localhost
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecom

  client:
    image: node:latest
    command: bash -c "npm install && npm start"
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    networks:
      - ecom

volumes:
  postgres_data:

networks:
  ecom:
    driver: bridge