# Generated by Django 5.0.1 on 2024-02-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userprofile_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='product_id',
            new_name='product',
        ),
    ]
