# Generated by Django 5.0.1 on 2024-03-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_stripe_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stripe_product_id',
            new_name='stripe_price_id',
        ),
    ]
